buildscript {
    // No repositories block here because it is managed by pluginManagement in settings.gradle
    dependencies {
        classpath "com.android.tools.build:gradle:8.1.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.10"
    }
}

allprojects {
    // Leave empty or remove repositories here due to the repositoriesMode setting
}
