name: Build Firebase Chat APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk: 21.4.7075529

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Decode wrapper jar
        run: bash .github/scripts/decode-wrapper.sh

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Create config.json
        run: |
          mkdir -p app/src/main/assets
          cat << EOF > app/src/main/assets/config.json
          {
            "mistrel_api_key": "${{ secrets.MISTREL_API_KEY }}",
            "mistrel_endpoint": "https://api.githubmistrel.com/v1/chat",
            "elevenlabs_api_key": "${{ secrets.ELEVENLABS_API_KEY }}",
            "elevenlabs_voice_id": "${{ secrets.ELEVENLABS_VOICE_ID }}"
          }
          EOF

      - name: Build Release APK
        run: |
          ./gradlew clean
          ./gradlew :app:assembleRelease --stacktrace --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: firebase-chat-apk
          path: app/build/outputs/apk/release/app-release.apk
